spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:maindb
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
#      data-locations: data.sql
#      schema-locations: schema.sql

management:
  endpoint:
    logfile:
      enabled: true
    health:
      show-details: always
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,logfile,mappings

logging:
  file:
    name: logs/application.log