spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: user_db
      port: 27017
      host: localhost
  shell:
    command:
      quit:
        enabled: false

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: INFO
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    org.mongodb.driver.protocol.command: DEBUG
#    org.mongodb.driver: DEBUG

